// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: resources/Book.proto

package com.jooq.h2.spring;

public final class BookDataProto {
  private BookDataProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface BookListOrBuilder extends
      // @@protoc_insertion_point(interface_extends:baeldung.BookList)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .baeldung.Book book = 1;</code>
     */
    java.util.List<com.jooq.h2.spring.BookDataProto.Book> 
        getBookList();
    /**
     * <code>repeated .baeldung.Book book = 1;</code>
     */
    com.jooq.h2.spring.BookDataProto.Book getBook(int index);
    /**
     * <code>repeated .baeldung.Book book = 1;</code>
     */
    int getBookCount();
    /**
     * <code>repeated .baeldung.Book book = 1;</code>
     */
    java.util.List<? extends com.jooq.h2.spring.BookDataProto.BookOrBuilder> 
        getBookOrBuilderList();
    /**
     * <code>repeated .baeldung.Book book = 1;</code>
     */
    com.jooq.h2.spring.BookDataProto.BookOrBuilder getBookOrBuilder(
            int index);
  }
  /**
   * Protobuf type {@code baeldung.BookList}
   */
  public  static final class BookList extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:baeldung.BookList)
      BookListOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use BookList.newBuilder() to construct.
    private BookList(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private BookList() {
      book_ = java.util.Collections.emptyList();
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private BookList(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                book_ = new java.util.ArrayList<com.jooq.h2.spring.BookDataProto.Book>();
                mutable_bitField0_ |= 0x00000001;
              }
              book_.add(
                  input.readMessage(com.jooq.h2.spring.BookDataProto.Book.parser(), extensionRegistry));
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          book_ = java.util.Collections.unmodifiableList(book_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return internal_static_baeldung_BookList_descriptor;
    }

    @Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return internal_static_baeldung_BookList_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.jooq.h2.spring.BookDataProto.BookList.class, com.jooq.h2.spring.BookDataProto.BookList.Builder.class);
    }

    public static final int BOOK_FIELD_NUMBER = 1;
    private java.util.List<com.jooq.h2.spring.BookDataProto.Book> book_;
    /**
     * <code>repeated .baeldung.Book book = 1;</code>
     */
    public java.util.List<com.jooq.h2.spring.BookDataProto.Book> getBookList() {
      return book_;
    }
    /**
     * <code>repeated .baeldung.Book book = 1;</code>
     */
    public java.util.List<? extends com.jooq.h2.spring.BookDataProto.BookOrBuilder>
        getBookOrBuilderList() {
      return book_;
    }
    /**
     * <code>repeated .baeldung.Book book = 1;</code>
     */
    public int getBookCount() {
      return book_.size();
    }
    /**
     * <code>repeated .baeldung.Book book = 1;</code>
     */
    public com.jooq.h2.spring.BookDataProto.Book getBook(int index) {
      return book_.get(index);
    }
    /**
     * <code>repeated .baeldung.Book book = 1;</code>
     */
    public com.jooq.h2.spring.BookDataProto.BookOrBuilder getBookOrBuilder(
        int index) {
      return book_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < book_.size(); i++) {
        output.writeMessage(1, book_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < book_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, book_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.jooq.h2.spring.BookDataProto.BookList)) {
        return super.equals(obj);
      }
      com.jooq.h2.spring.BookDataProto.BookList other = (com.jooq.h2.spring.BookDataProto.BookList) obj;

      boolean result = true;
      result = result && getBookList()
          .equals(other.getBookList());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getBookCount() > 0) {
        hash = (37 * hash) + BOOK_FIELD_NUMBER;
        hash = (53 * hash) + getBookList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.jooq.h2.spring.BookDataProto.BookList parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.jooq.h2.spring.BookDataProto.BookList parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.jooq.h2.spring.BookDataProto.BookList parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.jooq.h2.spring.BookDataProto.BookList parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.jooq.h2.spring.BookDataProto.BookList parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.jooq.h2.spring.BookDataProto.BookList parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.jooq.h2.spring.BookDataProto.BookList parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.jooq.h2.spring.BookDataProto.BookList parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.jooq.h2.spring.BookDataProto.BookList parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.jooq.h2.spring.BookDataProto.BookList parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.jooq.h2.spring.BookDataProto.BookList parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.jooq.h2.spring.BookDataProto.BookList parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.jooq.h2.spring.BookDataProto.BookList prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code baeldung.BookList}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:baeldung.BookList)
        com.jooq.h2.spring.BookDataProto.BookListOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return internal_static_baeldung_BookList_descriptor;
      }

      @Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return internal_static_baeldung_BookList_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.jooq.h2.spring.BookDataProto.BookList.class, com.jooq.h2.spring.BookDataProto.BookList.Builder.class);
      }

      // Construct using com.jooq.h2.spring.BookDataProto.BookList.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getBookFieldBuilder();
        }
      }
      @Override
      public Builder clear() {
        super.clear();
        if (bookBuilder_ == null) {
          book_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          bookBuilder_.clear();
        }
        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return internal_static_baeldung_BookList_descriptor;
      }

      @Override
      public com.jooq.h2.spring.BookDataProto.BookList getDefaultInstanceForType() {
        return getDefaultInstance();
      }

      @Override
      public com.jooq.h2.spring.BookDataProto.BookList build() {
        com.jooq.h2.spring.BookDataProto.BookList result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public com.jooq.h2.spring.BookDataProto.BookList buildPartial() {
        com.jooq.h2.spring.BookDataProto.BookList result = new com.jooq.h2.spring.BookDataProto.BookList(this);
        int from_bitField0_ = bitField0_;
        if (bookBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            book_ = java.util.Collections.unmodifiableList(book_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.book_ = book_;
        } else {
          result.book_ = bookBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.jooq.h2.spring.BookDataProto.BookList) {
          return mergeFrom((com.jooq.h2.spring.BookDataProto.BookList)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.jooq.h2.spring.BookDataProto.BookList other) {
        if (other == getDefaultInstance()) return this;
        if (bookBuilder_ == null) {
          if (!other.book_.isEmpty()) {
            if (book_.isEmpty()) {
              book_ = other.book_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureBookIsMutable();
              book_.addAll(other.book_);
            }
            onChanged();
          }
        } else {
          if (!other.book_.isEmpty()) {
            if (bookBuilder_.isEmpty()) {
              bookBuilder_.dispose();
              bookBuilder_ = null;
              book_ = other.book_;
              bitField0_ = (bitField0_ & ~0x00000001);
              bookBuilder_ =
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getBookFieldBuilder() : null;
            } else {
              bookBuilder_.addAllMessages(other.book_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.jooq.h2.spring.BookDataProto.BookList parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.jooq.h2.spring.BookDataProto.BookList) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<com.jooq.h2.spring.BookDataProto.Book> book_ =
        java.util.Collections.emptyList();
      private void ensureBookIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          book_ = new java.util.ArrayList<com.jooq.h2.spring.BookDataProto.Book>(book_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.jooq.h2.spring.BookDataProto.Book, com.jooq.h2.spring.BookDataProto.Book.Builder, com.jooq.h2.spring.BookDataProto.BookOrBuilder> bookBuilder_;

      /**
       * <code>repeated .baeldung.Book book = 1;</code>
       */
      public java.util.List<com.jooq.h2.spring.BookDataProto.Book> getBookList() {
        if (bookBuilder_ == null) {
          return java.util.Collections.unmodifiableList(book_);
        } else {
          return bookBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .baeldung.Book book = 1;</code>
       */
      public int getBookCount() {
        if (bookBuilder_ == null) {
          return book_.size();
        } else {
          return bookBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .baeldung.Book book = 1;</code>
       */
      public com.jooq.h2.spring.BookDataProto.Book getBook(int index) {
        if (bookBuilder_ == null) {
          return book_.get(index);
        } else {
          return bookBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .baeldung.Book book = 1;</code>
       */
      public Builder setBook(
          int index, com.jooq.h2.spring.BookDataProto.Book value) {
        if (bookBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureBookIsMutable();
          book_.set(index, value);
          onChanged();
        } else {
          bookBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .baeldung.Book book = 1;</code>
       */
      public Builder setBook(
          int index, com.jooq.h2.spring.BookDataProto.Book.Builder builderForValue) {
        if (bookBuilder_ == null) {
          ensureBookIsMutable();
          book_.set(index, builderForValue.build());
          onChanged();
        } else {
          bookBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .baeldung.Book book = 1;</code>
       */
      public Builder addBook(com.jooq.h2.spring.BookDataProto.Book value) {
        if (bookBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureBookIsMutable();
          book_.add(value);
          onChanged();
        } else {
          bookBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .baeldung.Book book = 1;</code>
       */
      public Builder addBook(
          int index, com.jooq.h2.spring.BookDataProto.Book value) {
        if (bookBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureBookIsMutable();
          book_.add(index, value);
          onChanged();
        } else {
          bookBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .baeldung.Book book = 1;</code>
       */
      public Builder addBook(
          com.jooq.h2.spring.BookDataProto.Book.Builder builderForValue) {
        if (bookBuilder_ == null) {
          ensureBookIsMutable();
          book_.add(builderForValue.build());
          onChanged();
        } else {
          bookBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .baeldung.Book book = 1;</code>
       */
      public Builder addBook(
          int index, com.jooq.h2.spring.BookDataProto.Book.Builder builderForValue) {
        if (bookBuilder_ == null) {
          ensureBookIsMutable();
          book_.add(index, builderForValue.build());
          onChanged();
        } else {
          bookBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .baeldung.Book book = 1;</code>
       */
      public Builder addAllBook(
          Iterable<? extends com.jooq.h2.spring.BookDataProto.Book> values) {
        if (bookBuilder_ == null) {
          ensureBookIsMutable();
          addAll(
              values, book_);
          onChanged();
        } else {
          bookBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .baeldung.Book book = 1;</code>
       */
      public Builder clearBook() {
        if (bookBuilder_ == null) {
          book_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          bookBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .baeldung.Book book = 1;</code>
       */
      public Builder removeBook(int index) {
        if (bookBuilder_ == null) {
          ensureBookIsMutable();
          book_.remove(index);
          onChanged();
        } else {
          bookBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .baeldung.Book book = 1;</code>
       */
      public com.jooq.h2.spring.BookDataProto.Book.Builder getBookBuilder(
          int index) {
        return getBookFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .baeldung.Book book = 1;</code>
       */
      public com.jooq.h2.spring.BookDataProto.BookOrBuilder getBookOrBuilder(
          int index) {
        if (bookBuilder_ == null) {
          return book_.get(index);  } else {
          return bookBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .baeldung.Book book = 1;</code>
       */
      public java.util.List<? extends com.jooq.h2.spring.BookDataProto.BookOrBuilder>
           getBookOrBuilderList() {
        if (bookBuilder_ != null) {
          return bookBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(book_);
        }
      }
      /**
       * <code>repeated .baeldung.Book book = 1;</code>
       */
      public com.jooq.h2.spring.BookDataProto.Book.Builder addBookBuilder() {
        return getBookFieldBuilder().addBuilder(
            com.jooq.h2.spring.BookDataProto.Book.getDefaultInstance());
      }
      /**
       * <code>repeated .baeldung.Book book = 1;</code>
       */
      public com.jooq.h2.spring.BookDataProto.Book.Builder addBookBuilder(
          int index) {
        return getBookFieldBuilder().addBuilder(
            index, com.jooq.h2.spring.BookDataProto.Book.getDefaultInstance());
      }
      /**
       * <code>repeated .baeldung.Book book = 1;</code>
       */
      public java.util.List<com.jooq.h2.spring.BookDataProto.Book.Builder>
           getBookBuilderList() {
        return getBookFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.jooq.h2.spring.BookDataProto.Book, com.jooq.h2.spring.BookDataProto.Book.Builder, com.jooq.h2.spring.BookDataProto.BookOrBuilder>
          getBookFieldBuilder() {
        if (bookBuilder_ == null) {
          bookBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              com.jooq.h2.spring.BookDataProto.Book, com.jooq.h2.spring.BookDataProto.Book.Builder, com.jooq.h2.spring.BookDataProto.BookOrBuilder>(
                  book_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          book_ = null;
        }
        return bookBuilder_;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:baeldung.BookList)
    }

    // @@protoc_insertion_point(class_scope:baeldung.BookList)
    private static final com.jooq.h2.spring.BookDataProto.BookList DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.jooq.h2.spring.BookDataProto.BookList();
    }

    public static com.jooq.h2.spring.BookDataProto.BookList getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<BookList>
        PARSER = new com.google.protobuf.AbstractParser<BookList>() {
      @Override
      public BookList parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new BookList(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<BookList> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<BookList> getParserForType() {
      return PARSER;
    }

    @Override
    public com.jooq.h2.spring.BookDataProto.BookList getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface BookOrBuilder extends
      // @@protoc_insertion_point(interface_extends:baeldung.Book)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 published = 3;</code>
     */
    int getPublished();

    /**
     * <code>int32 authorId = 2;</code>
     */
    int getAuthorId();

    /**
     * <code>string bookTitle = 1;</code>
     */
    String getBookTitle();
    /**
     * <code>string bookTitle = 1;</code>
     */
    com.google.protobuf.ByteString
        getBookTitleBytes();
  }
  /**
   * Protobuf type {@code baeldung.Book}
   */
  public  static final class Book extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:baeldung.Book)
      BookOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Book.newBuilder() to construct.
    private Book(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Book() {
      published_ = 0;
      authorId_ = 0;
      bookTitle_ = "";
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Book(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              String s = input.readStringRequireUtf8();

              bookTitle_ = s;
              break;
            }
            case 16: {

              authorId_ = input.readInt32();
              break;
            }
            case 24: {

              published_ = input.readInt32();
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return internal_static_baeldung_Book_descriptor;
    }

    @Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return internal_static_baeldung_Book_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.jooq.h2.spring.BookDataProto.Book.class, com.jooq.h2.spring.BookDataProto.Book.Builder.class);
    }

    public static final int PUBLISHED_FIELD_NUMBER = 3;
    private int published_;
    /**
     * <code>int32 published = 3;</code>
     */
    public int getPublished() {
      return published_;
    }

    public static final int AUTHORID_FIELD_NUMBER = 2;
    private int authorId_;
    /**
     * <code>int32 authorId = 2;</code>
     */
    public int getAuthorId() {
      return authorId_;
    }

    public static final int BOOKTITLE_FIELD_NUMBER = 1;
    private volatile Object bookTitle_;
    /**
     * <code>string bookTitle = 1;</code>
     */
    public String getBookTitle() {
      Object ref = bookTitle_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        bookTitle_ = s;
        return s;
      }
    }
    /**
     * <code>string bookTitle = 1;</code>
     */
    public com.google.protobuf.ByteString
        getBookTitleBytes() {
      Object ref = bookTitle_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        bookTitle_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getBookTitleBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, bookTitle_);
      }
      if (authorId_ != 0) {
        output.writeInt32(2, authorId_);
      }
      if (published_ != 0) {
        output.writeInt32(3, published_);
      }
      unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getBookTitleBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, bookTitle_);
      }
      if (authorId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, authorId_);
      }
      if (published_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, published_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.jooq.h2.spring.BookDataProto.Book)) {
        return super.equals(obj);
      }
      com.jooq.h2.spring.BookDataProto.Book other = (com.jooq.h2.spring.BookDataProto.Book) obj;

      boolean result = true;
      result = result && (getPublished()
          == other.getPublished());
      result = result && (getAuthorId()
          == other.getAuthorId());
      result = result && getBookTitle()
          .equals(other.getBookTitle());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + PUBLISHED_FIELD_NUMBER;
      hash = (53 * hash) + getPublished();
      hash = (37 * hash) + AUTHORID_FIELD_NUMBER;
      hash = (53 * hash) + getAuthorId();
      hash = (37 * hash) + BOOKTITLE_FIELD_NUMBER;
      hash = (53 * hash) + getBookTitle().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.jooq.h2.spring.BookDataProto.Book parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.jooq.h2.spring.BookDataProto.Book parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.jooq.h2.spring.BookDataProto.Book parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.jooq.h2.spring.BookDataProto.Book parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.jooq.h2.spring.BookDataProto.Book parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.jooq.h2.spring.BookDataProto.Book parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.jooq.h2.spring.BookDataProto.Book parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.jooq.h2.spring.BookDataProto.Book parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.jooq.h2.spring.BookDataProto.Book parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.jooq.h2.spring.BookDataProto.Book parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.jooq.h2.spring.BookDataProto.Book parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.jooq.h2.spring.BookDataProto.Book parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.jooq.h2.spring.BookDataProto.Book prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code baeldung.Book}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:baeldung.Book)
        com.jooq.h2.spring.BookDataProto.BookOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return internal_static_baeldung_Book_descriptor;
      }

      @Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return internal_static_baeldung_Book_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.jooq.h2.spring.BookDataProto.Book.class, com.jooq.h2.spring.BookDataProto.Book.Builder.class);
      }

      // Construct using com.jooq.h2.spring.BookDataProto.Book.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @Override
      public Builder clear() {
        super.clear();
        published_ = 0;

        authorId_ = 0;

        bookTitle_ = "";

        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return internal_static_baeldung_Book_descriptor;
      }

      @Override
      public com.jooq.h2.spring.BookDataProto.Book getDefaultInstanceForType() {
        return getDefaultInstance();
      }

      @Override
      public com.jooq.h2.spring.BookDataProto.Book build() {
        com.jooq.h2.spring.BookDataProto.Book result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public com.jooq.h2.spring.BookDataProto.Book buildPartial() {
        com.jooq.h2.spring.BookDataProto.Book result = new com.jooq.h2.spring.BookDataProto.Book(this);
        result.published_ = published_;
        result.authorId_ = authorId_;
        result.bookTitle_ = bookTitle_;
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.jooq.h2.spring.BookDataProto.Book) {
          return mergeFrom((com.jooq.h2.spring.BookDataProto.Book)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.jooq.h2.spring.BookDataProto.Book other) {
        if (other == getDefaultInstance()) return this;
        if (other.getPublished() != 0) {
          setPublished(other.getPublished());
        }
        if (other.getAuthorId() != 0) {
          setAuthorId(other.getAuthorId());
        }
        if (!other.getBookTitle().isEmpty()) {
          bookTitle_ = other.bookTitle_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.jooq.h2.spring.BookDataProto.Book parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.jooq.h2.spring.BookDataProto.Book) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int published_ ;
      /**
       * <code>int32 published = 3;</code>
       */
      public int getPublished() {
        return published_;
      }
      /**
       * <code>int32 published = 3;</code>
       */
      public Builder setPublished(int value) {

        published_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 published = 3;</code>
       */
      public Builder clearPublished() {

        published_ = 0;
        onChanged();
        return this;
      }

      private int authorId_ ;
      /**
       * <code>int32 authorId = 2;</code>
       */
      public int getAuthorId() {
        return authorId_;
      }
      /**
       * <code>int32 authorId = 2;</code>
       */
      public Builder setAuthorId(int value) {

        authorId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 authorId = 2;</code>
       */
      public Builder clearAuthorId() {

        authorId_ = 0;
        onChanged();
        return this;
      }

      private Object bookTitle_ = "";
      /**
       * <code>string bookTitle = 1;</code>
       */
      public String getBookTitle() {
        Object ref = bookTitle_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          bookTitle_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string bookTitle = 1;</code>
       */
      public com.google.protobuf.ByteString
          getBookTitleBytes() {
        Object ref = bookTitle_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          bookTitle_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string bookTitle = 1;</code>
       */
      public Builder setBookTitle(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }

        bookTitle_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string bookTitle = 1;</code>
       */
      public Builder clearBookTitle() {

        bookTitle_ = getDefaultInstance().getBookTitle();
        onChanged();
        return this;
      }
      /**
       * <code>string bookTitle = 1;</code>
       */
      public Builder setBookTitleBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);

        bookTitle_ = value;
        onChanged();
        return this;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:baeldung.Book)
    }

    // @@protoc_insertion_point(class_scope:baeldung.Book)
    private static final com.jooq.h2.spring.BookDataProto.Book DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.jooq.h2.spring.BookDataProto.Book();
    }

    public static com.jooq.h2.spring.BookDataProto.Book getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Book>
        PARSER = new com.google.protobuf.AbstractParser<Book>() {
      @Override
      public Book parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Book(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Book> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<Book> getParserForType() {
      return PARSER;
    }

    @Override
    public com.jooq.h2.spring.BookDataProto.Book getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_baeldung_BookList_descriptor;
  private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_baeldung_BookList_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_baeldung_Book_descriptor;
  private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_baeldung_Book_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\024resources/Book.proto\022\010baeldung\"(\n\010Book" +
      "List\022\034\n\004book\030\001 \003(\0132\016.baeldung.Book\">\n\004Bo" +
      "ok\022\021\n\tpublished\030\003 \001(\005\022\020\n\010authorId\030\002 \001(\005\022" +
      "\021\n\tbookTitle\030\001 \001(\tB#\n\022com.jooq.h2.spring" +
      "B\rBookDataProtob\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_baeldung_BookList_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_baeldung_BookList_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_baeldung_BookList_descriptor,
        new String[] { "Book", });
    internal_static_baeldung_Book_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_baeldung_Book_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_baeldung_Book_descriptor,
        new String[] { "Published", "AuthorId", "BookTitle", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
